/*
*****************************************************************************
**
**      Project     : KAWE_76032
**
**      Component   : MAIN (LPC1225)
**
**      Modulename  : PUBLIC
**
**      Filename    : Main.c
**
**      Abstract    : This is the device driver  file for the RTX real time chip 
**                    module.
**
**      Compiler    : KEIL C compiler
**
**      Date        : 2014-09-28 16:31:15
**
**      License no. : 9538-154-209-9667     Frank Tsang
**
**      Warning     : This file has been automatically generated.
**                    Do not edit this file if you intend to regenerate it.
**
**      This device driver was created by IAR MakeApp version 
**      4.10C (Atmel megaAVR: 4.00B) for the Atmel megaAVR series of
**      microcontrollers.
**
**      (c)Copyright 2003 IAR Systems.
**      Your rights to this file are explained in the IAR MakeApp 
**      License Agreement. All other rights reserved.
**
*****************************************************************************
*/

/*
**===========================================================================
**  1       GENERAL
**  1.1     Revisions
**
**  Please read the IAR MakeApp for Atmel megaAVR readme file 
**  V1.0
**
**===========================================================================
*/

/*
**===========================================================================
**  1.2     References
** 
**  No   Identification          Name or Description
**===========================================================================
**  
** 
**===========================================================================
*/

/*
**===========================================================================
**  2.      INCLUDE FILES
**  2.1     Standard include files
**===========================================================================
*/

#include "lpc12xx.h"
#include "core_cm0.h"
#include "lpc_types.h"
#include <stdlib.h>
#include <stdio.h>

#include <RTL.h> 
//#include "RT_Agent.h"
#include "Lpc12xx_libcfg_default.h"


/*
**===========================================================================
**  2.2     Application include files
**===========================================================================
*/
#ifndef _IS_INCLUDED_MAIN_C_
#define _IS_INCLUDED_MAIN_C_

#include "Main.h"

//#include "Lpc12xx_gpio.h"
//#include "Lpc12xx_uart.h"
//#include "Debug_frmwrk.h"
#include "Uart.h"
#include "Time.h"
#include "LedTask.h"
#include "MdbSlaveTask.h"
#include "ComHostTask.h"
#include "BillValidator.h"
#endif

/*
**===========================================================================
**  3.      DECLARATIONS
**  3.1     Internal constants
**===========================================================================
*/


/*
**===========================================================================
**  3.2     Internal macros
**===========================================================================
*/

/*
**===========================================================================
**  3.3     Internal type definitions
**===========================================================================
*/

/*
**===========================================================================
**  3.4     Global variables (declared as 'extern' in some header file)
**===========================================================================
*/


/*
**===========================================================================
**  3.5     Internal function prototypes (defined in Section 5)
**===========================================================================
*/

/*
**===========================================================================
**  3.6     Internal variables
**===========================================================================
*/
//static	U64	stk_VtsSlave[1024 / 8];
//static	U8	stk_ComHost[256];
//static	U64	stk_ComSlave[1024 / 8];
//static	U64	stk_MdbHost[1024 / 8];
//static	U8	stk_MdbSlave[256];

//static	U8	stk_Led[128];
//static	U8	stk_LedMdb[128];
//static	U8	stk_LedCom[128];


/*-------------------------------------------------------------------------
	service functions comments
	
-------------------------------------------------------------------------*/
#if 0
__task void tsk_VtsSlave(void)
{
	os_tsk_prio_self(250);

	
	for (;;)
	{
		os_sem_wait(&sem_VtsSlave_Rx, 0xFFFF);
			
	}
}
#endif	
	

	
/*-------------------------------------------------------------------------
	service functions comments
	
-------------------------------------------------------------------------*/
#if 0
__task void tsk_ComSlave(void)
{
	//os_tsk_prio_self(250);
	os_dly_wait(100);
	
	for (;;)
	{
		os_sem_wait(&sem_ComSlave_Rx, 0xFFFF);
			
	}
}
#endif	
	
/*-------------------------------------------------------------------------
	service functions comments
	
-------------------------------------------------------------------------*/
#if 0
__task void tsk_MdbHost(void)
{
	//os_tsk_prio_self(250);
	os_dly_wait(200);
	
	for (;;)
	{
		os_sem_wait(&sem_MdbHost_Rx, 0xFFFF);
			
	}
}
#endif

	


#if 0
__task void tsk_Led_Mdb(void)	//
{
	for (;;)
	{
		if (u8_MdbSlave_State < WS_ENABLED)//(u8_Shakehands == 0)
		{
			os_dly_wait(6);	// 60ms
		}
		else
		{
			os_dly_wait(50);	// 500ms
		}

		MDB_LedFlash();
	}	
}
#endif

#if 0
__task void tsk_Led_Com(void)	//
{
	for (;;)
	{
		if (u8_ComHost_State < COMHOST_ENABLE)//(u8_Shakehands == 0)
		{
			os_dly_wait(6);	// 60ms
		}
		else
		{
			os_dly_wait(50);	// 500ms
		}

		COM_LedFlash();
	}	
}
#endif

/*-------------------------------------------------------------------------
	service functions comments	
-------------------------------------------------------------------------*/
#if 1
__task void tsk_System_Initial(void)							//任务1
{
	tid_MdbSlave = os_tsk_create(tsk_MdbSlave, 20);	//MDB从机任务	
	tid_ComHost	 = os_tsk_create(tsk_ComHost, 10);		//串口232任务
	os_tsk_create(tsk_Led, 2);												//LED任务

	os_tsk_delete_self();
}
#endif

void Device_Init(void)	//设备硬件初始化
{
	SystemInit();					//时钟
	
	Uart_Mode_Init();			// Initial the uarts mode according to the SEL0&SEL1
	Uart_Init_ComHost();	// Uart1
	Uart_Init_MdbSlave();	// Uart0
	Timer_Init_MdbSlave();
}

/*******************************************************************************
  函数名称：main
	函数说明：主函数
	输入参数：
	输出参数：
	返回参数：
  *****************************************************************************/
int  main(void)
{
	Device_Init();
	os_sys_init_prio(tsk_System_Initial, 250);
}
/*
**===========================================================================
** END OF FILE
**===========================================================================
*/ 
