
/*
*****************************************************************************
**
**      Project     : KAWE_76032
**
**      Component   : TIME (LPC1225)
**
**      Modulename  : PUBLIC
**
**      Filename    : Time.h
**
**      Abstract    : This is the device driver header file for the RXT real time chip 
**                    module.
**
**      Compiler    : KEIL C compiler
**
**      Date        : 2012-11-16 16:31:15
**
**      License no. : 9538-154-209-9667     Frank Tsang
**
**      Warning     : This file has been automatically generated.
**                    Do not edit this file if you intend to regenerate it.
**
**      This device driver was created by IAR MakeApp version 
**      4.10C (Atmel megaAVR: 4.00B) for the Atmel megaAVR series of
**      microcontrollers.
**
**      (c)Copyright 2003 IAR Systems.
**      Your rights to this file are explained in the IAR MakeApp 
**      License Agreement. All other rights reserved.
**
*****************************************************************************
*/

/*
**===========================================================================
**  1       GENERAL
**  1.1     Revisions
**
**  Please read the IAR MakeApp for Atmel megaAVR readme file 
**  V1.0
**
**===========================================================================
*/

/*
**===========================================================================
**  1.2     References
** 
**  No   Identification          Name or Description
**  ==   ===================     ================================
**  
** 
**===========================================================================
*/

/*
**===========================================================================
**  1.3     Re-definition guard
**===========================================================================
*/

/*--- Avoid including this file more than once ---*/
#ifndef _IS_INCLUDED_TIME_H_
#define _IS_INCLUDED_TIME_H_

/*
**===========================================================================
**  2.      INCLUDE FILES
**  2.1     Standard include files
**===========================================================================
*/
#include <lpc12xx.h>
#include <core_cm0.h>
#include <lpc_types.h>
#include <stdlib.h>
#include <stdio.h>
	
#include <RTL.h> 
//#include "RT_Agent.h"
//#include "RTX_Libs.h"
	

/*
**===========================================================================
**  2.2     Application include files
**===========================================================================
*/


//#include "typedef.h"


/*
**===========================================================================
**  3.      DECLARATIONS
**  3.1     Global constants
**===========================================================================
*/


#if 0
enum{
	TSK_SELF	      = 0,
//	NO_TASK            	= 0,
//	NULL_MBX            = 0
};
#endif



/*
**===========================================================================
**  3.2     Global macros
**===========================================================================
*/








/*
**===========================================================================
**  3.3     Global type definitions
**===========================================================================
*/

#if 0
typedef struct 
{
  	OS_TID 		task;
  	OS_ID  		timer;
  	T_TIK  		initial_period;
  	T_TIK  		cycle_time;
  	T_SEM   	sema;
	U16			updateFlag;
  	U32    		timVal;
  	U16    		info;	//ndx;     the info parameter in os_tmr_call()
} T_TMR;		// type of system timer
#endif
 



/*
**===========================================================================
**  3.4     Global variables (defined in some implementation file)
**===========================================================================
*/
#ifdef	_IS_INCLUDED_TIME_C_
	#define	PUBLIC
#else
	#define	PUBLIC	extern
#endif


//PUBLIC		T_TMR 			TmrArray[SUM_TMR];

//PUBLIC 	volatile	T_SEM	SemaSysTmr;


/*
**===========================================================================
**  4.      GLOBAL FUNCTIONS (defined in some implementation file)
**===========================================================================
*/

//PUBLIC		void 		rtx_Tmr_Init(void);
PUBLIC	void TIMER32_0_IRQHandler(void);
//PUBLIC	void TIMER32_1_IRQHandler(void);
PUBLIC	void Timer_Init_MdbSlave(void);
//PUBLIC	void Timer_Init_ComHost(void);
PUBLIC	void Timer_Start_MdbSlave( U16 u16_10usUnits );
//PUBLIC	void Timer_Start_ComHost( U16 u16_1msUnits );
PUBLIC	void Timer_Stop_MdbSlave( void );
//PUBLIC	void Timer_Stop_ComHost( void );

//PUBLIC	void MdbSlave_Timer_IRQHandler(void);



#undef	PUBLIC

#endif /* Match the re-definition guard */


/*
**===========================================================================
** END OF FILE
**===========================================================================
*/ 

